export const updateTimelineItemActivitySecondsKey = Symbol()
export const timelineItemsKey= Symbol()
export const activitySelectOptionsKey= Symbol()
export const periodSelectOptionsKey = Symbol()
export const setTimelineItemActivityKey = Symbol()
export const setActivitySecondsToCompleteKey = Symbol()
export const createActivityKey = Symbol()
export const deleteActivityKey = Symbol()
